baseURL = "http://mattzirp.github.io/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Matthew Zirpoli"
languageCode = "en"
languageName = "English"
enableGitInfo = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About Me"
    url = "/about/"
    # title will be shown when you hover on this menu link
    title = "My Career Journey, Skills, and Resume"
  [[menu.main]]
    weight = 2
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
[params]
  defaultTheme = "auto"
  gitRepo = "https://github.com/mattzirp/mattzirp.github.io"
  dateFormat = "2006-01-02"
  title = "Matt Zirpoli"
  description = "Matt Zirpoli - Data Science"
  [params.author]
    name = "Matthew Zirpoli"
    email = "zirpoli.matthew@gmail.com"
    link = "https://github.com/mattzirp/"

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      logo = ""
      name = "Matthew Zirpoli"
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ""
    hugo = true
    copyright = true
    author = true
    since = 2025
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

    [params.home]
    rss = 10
    # Home page profile
    # 主页个人信息
    [params.home.profile]
      enable = true
      avatarURL = "/headshot.png"
      title = "Matthew Zirpoli"
      subtitle = "From Process to Prediction: An engineer's path through IT and Data Science"
      typeit = true
      social = true
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "mattzirp/"
    Linkedin = "mattzirp/"
    Email = "zirpoli.matthew@gmail.com"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false